name: "Podcast Generator"
description: "Gnerates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  using: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committer's email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}